#!/usr/bin/env python

import os
import sys
from urllib.parse import urlparse, parse_qs
import requests
import hashlib


def generate_hash(input_str: str, length: int=16) -> str:
    hash_digest = hashlib.blake2b(input_str.encode(), digest_size=8).hexdigest()
    return hash_digest[:length]

def extract_video_id(url: str) -> str:
    parsed_url = urlparse(url)
    try:
        query = parse_qs(parsed_url.query, strict_parsing=True)
    except ValueError:
        print("Error: Invalid YouTube URL.")
    try:
        video_id = query.get("v", [""])[0]
    except IndexError:
        print("Error: Parsing video ID.")
    return video_id

def download_thumbnail(url: str) -> None:
    downloads_path = os.path.expanduser("~/Downloads")
    video_id = extract_video_id(url)

    if not video_id:
        print("Error: Invalid YouTube URL.")
        sys.exit(1)
 
    res = None
    valid_urls = [
        f"https://i.ytimg.com/vi_webp/{video_id}/maxresdefault.webp", 
        f"https://i.ytimg.com/vi_webp/{video_id}/hqdefault.webp", 
        f"https://i.ytimg.com/vi_webp/{video_id}/default.webp"
    ] 

    for thumbnail_url in valid_urls:
        res = requests.get(thumbnail_url, stream=True)
        if res.status_code == 200:
            break

    if res.status_code != 200:
        print(f"HTTP Status Code: {res.status_code}")
        print("Failed to download thumbnail.")
        sys.exit(1)

    filename = generate_hash(video_id, 16) + ".webp"
    file_path = os.path.join(downloads_path, filename)

    with open(file_path, 'wb') as file:
        for chunk in res.iter_content(chunk_size=128):
            file.write(chunk)
    
    print(f"Thumbnail Saved: {file_path}")

def main() -> None:
    if (len(sys.argv) != 2) or (sys.argv[1] in ("-h", "--help")):
        print("Usage: yt-thumbnail <YouTube Video URL>")
        print("Description: This script downloads the YouTube video thumbnail of the given URL.")
        sys.exit(1)

    yt_link = sys.argv[1]
    download_thumbnail(yt_link)

if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"Error: {error}")
        sys.exit(1)
    sys.exit(0)
